import PDFDocument from 'pdfkit';
import { StorageService } from './storageService.js';

export class PdfService {
  /**
   * Generate Prescription PDF
   */
  static async generatePrescriptionPdf(prescriptionData: any): Promise<string> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 40, size: 'A4' });
        const buffers: Buffer[] = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', async () => {
          const pdfBuffer = Buffer.concat(buffers);
          const saved = await StorageService.saveFile(
            pdfBuffer,
            `Prescription-${prescriptionData.prescriptionNumber}.pdf`,
            'prescriptions',
            'application/pdf'
          );
          resolve(saved.fileUrl);
        });

        // Header / Hospital Branding
        doc.fillColor('#0284c7').fontSize(20).text('MEDPULSE HEALTHCARE HOSPITAL', { align: 'center' });
        doc.fillColor('#64748b').fontSize(10).text('742 Evergreen Medical Park, New York, NY 10001 | Phone: +1 (555) 234-5678', { align: 'center' });
        doc.text('Web: www.medpulsehospital.com | Emergency: +1 (555) 911-0000', { align: 'center' });
        doc.moveDown(0.5);
        doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(40, doc.y).lineTo(555, doc.y).stroke();
        doc.moveDown(1);

        // Prescription Metadata
        doc.fillColor('#0f172a').fontSize(14).text('PRESCRIPTION & MEDICAL ADVICE', { underline: true });
        doc.moveDown(0.5);

        const startY = doc.y;
        doc.fontSize(10).fillColor('#334155');
        doc.text(`Prescription No: ${prescriptionData.prescriptionNumber}`, 40, startY);
        doc.text(`Date: ${new Date(prescriptionData.issueDate || Date.now()).toLocaleDateString()}`, 350, startY);

        doc.text(`Doctor: Dr. ${prescriptionData.doctorName}`, 40, startY + 16);
        doc.text(`Specialization: ${prescriptionData.doctorSpecialization || 'General Practitioner'}`, 350, startY + 16);

        doc.text(`Patient Name: ${prescriptionData.patientName}`, 40, startY + 32);
        doc.text(`Patient ID: ${prescriptionData.patientId || 'N/A'}`, 350, startY + 32);

        doc.text(`Age/Gender: ${prescriptionData.patientAge || '32'} yrs / ${prescriptionData.patientGender || 'N/A'}`, 40, startY + 48);
        doc.text(`Department: ${prescriptionData.departmentName || 'General Medicine'}`, 350, startY + 48);

        doc.y = startY + 70;
        doc.strokeColor('#e2e8f0').lineWidth(1).moveTo(40, doc.y).lineTo(555, doc.y).stroke();
        doc.moveDown(1);

        // Diagnosis
        doc.fontSize(11).fillColor('#0284c7').text('Diagnosis:');
        doc.fontSize(10).fillColor('#1e293b').text(prescriptionData.diagnosis || 'Clinical evaluation completed.');
        doc.moveDown(1);

        // Rx Table Header
        doc.fontSize(14).fillColor('#0284c7').text('Rx (Medications)', { underline: false });
        doc.moveDown(0.5);

        const tableTop = doc.y;
        doc.rect(40, tableTop, 515, 22).fill('#f1f5f9');
        doc.fillColor('#0f172a').fontSize(9).font('Helvetica-Bold');
        doc.text('#', 45, tableTop + 6);
        doc.text('Medicine Name', 70, tableTop + 6);
        doc.text('Dosage', 220, tableTop + 6);
        doc.text('Frequency', 290, tableTop + 6);
        doc.text('Duration', 370, tableTop + 6);
        doc.text('Instructions', 440, tableTop + 6);

        let rowY = tableTop + 24;
        doc.font('Helvetica').fontSize(9).fillColor('#334155');

        (prescriptionData.medicines || []).forEach((med: any, index: number) => {
          doc.text(`${index + 1}`, 45, rowY);
          doc.text(med.name || '', 70, rowY, { width: 140 });
          doc.text(med.dosage || '', 220, rowY);
          doc.text(med.frequency || '', 290, rowY);
          doc.text(med.duration || '', 370, rowY);
          doc.text(med.instructions || 'After meals', 440, rowY, { width: 110 });
          rowY += 24;
        });

        doc.y = Math.max(rowY + 20, 560);

        // Notes
        if (prescriptionData.notes) {
          doc.fontSize(10).fillColor('#0284c7').text('Special Instructions / Advice:');
          doc.fontSize(9).fillColor('#475569').text(prescriptionData.notes);
          doc.moveDown(1.5);
        }

        // Signature section
        const footerY = 700;
        doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(380, footerY).lineTo(540, footerY).stroke();
        doc.fontSize(10).fillColor('#0f172a').text(`Dr. ${prescriptionData.doctorName}`, 380, footerY + 5, { align: 'center', width: 160 });
        doc.fontSize(8).fillColor('#64748b').text('Authorized Medical Officer & Signature', 380, footerY + 18, { align: 'center', width: 160 });

        doc.fontSize(8).fillColor('#94a3b8').text('This is a verified digital prescription generated by MedPulse Hospital EMR System.', 40, 780, { align: 'center' });

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }

  /**
   * Generate Invoice PDF
   */
  static async generateInvoicePdf(invoiceData: any): Promise<string> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 40, size: 'A4' });
        const buffers: Buffer[] = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', async () => {
          const pdfBuffer = Buffer.concat(buffers);
          const saved = await StorageService.saveFile(
            pdfBuffer,
            `Invoice-${invoiceData.invoiceNumber}.pdf`,
            'documents',
            'application/pdf'
          );
          resolve(saved.fileUrl);
        });

        // Hospital Header
        doc.fillColor('#0284c7').fontSize(22).text('MEDPULSE HOSPITAL', 40, 40);
        doc.fillColor('#64748b').fontSize(9).text('Tax ID / Reg: MPH-9088219-US', 40, 65);
        doc.text('742 Evergreen Medical Park, New York, NY 10001', 40, 78);
        doc.text('Billing Support: billing@medpulsehospital.com | +1 (555) 234-5678', 40, 91);

        // Invoice Meta Right Box
        doc.fillColor('#0f172a').fontSize(16).text('TAX INVOICE', 380, 40, { align: 'right' });
        doc.fontSize(10).fillColor('#334155');
        doc.text(`Invoice #: ${invoiceData.invoiceNumber}`, 300, 65, { align: 'right' });
        doc.text(`Date: ${new Date(invoiceData.createdAt || Date.now()).toLocaleDateString()}`, 300, 78, { align: 'right' });
        doc.text(`Due Date: ${new Date(invoiceData.dueDate || Date.now()).toLocaleDateString()}`, 300, 91, { align: 'right' });
        doc.text(`Status: ${(invoiceData.paymentStatus || 'Pending').toUpperCase()}`, 300, 104, { align: 'right' });

        doc.strokeColor('#e2e8f0').lineWidth(1).moveTo(40, 125).lineTo(555, 125).stroke();

        // Billed To
        doc.fontSize(10).fillColor('#64748b').text('BILLED TO:', 40, 140);
        doc.fontSize(12).fillColor('#0f172a').text(invoiceData.patientName, 40, 155);
        doc.fontSize(9).fillColor('#475569');
        doc.text(`Patient ID: ${invoiceData.patientId || 'N/A'}`, 40, 170);
        doc.text(`Phone: ${invoiceData.patientPhone || 'N/A'}`, 40, 183);

        // Items Table
        const tableTop = 215;
        doc.rect(40, tableTop, 515, 22).fill('#0284c7');
        doc.fillColor('#ffffff').fontSize(9).font('Helvetica-Bold');
        doc.text('Item Description', 45, tableTop + 6);
        doc.text('Category', 240, tableTop + 6);
        doc.text('Qty', 350, tableTop + 6);
        doc.text('Unit Price ($)', 400, tableTop + 6);
        doc.text('Amount ($)', 480, tableTop + 6, { align: 'right', width: 65 });

        let itemY = tableTop + 24;
        doc.font('Helvetica').fontSize(9).fillColor('#1e293b');

        (invoiceData.items || []).forEach((item: any) => {
          doc.text(item.description, 45, itemY, { width: 180 });
          doc.text(item.category || 'Service', 240, itemY);
          doc.text(`${item.quantity}`, 350, itemY);
          doc.text(`$${Number(item.unitPrice).toFixed(2)}`, 400, itemY);
          doc.text(`$${Number(item.amount).toFixed(2)}`, 480, itemY, { align: 'right', width: 65 });
          itemY += 22;
        });

        doc.strokeColor('#e2e8f0').lineWidth(1).moveTo(40, itemY + 10).lineTo(555, itemY + 10).stroke();

        // Summary calculations
        const totalsY = itemY + 20;
        doc.fontSize(10).fillColor('#475569');
        doc.text('Subtotal:', 350, totalsY);
        doc.text(`$${Number(invoiceData.subtotal || 0).toFixed(2)}`, 460, totalsY, { align: 'right', width: 85 });

        doc.text('Discount:', 350, totalsY + 18);
        doc.text(`-$${Number(invoiceData.discount || 0).toFixed(2)}`, 460, totalsY + 18, { align: 'right', width: 85 });

        doc.text('Tax / VAT (5%):', 350, totalsY + 36);
        doc.text(`$${Number(invoiceData.tax || 0).toFixed(2)}`, 460, totalsY + 36, { align: 'right', width: 85 });

        doc.rect(340, totalsY + 54, 215, 26).fill('#f8fafc');
        doc.font('Helvetica-Bold').fontSize(11).fillColor('#0284c7');
        doc.text('Total Amount Due:', 350, totalsY + 62);
        doc.text(`$${Number(invoiceData.totalAmount || 0).toFixed(2)}`, 460, totalsY + 62, { align: 'right', width: 85 });

        doc.font('Helvetica').fontSize(9).fillColor('#64748b');
        doc.text('Payment methods accepted: Credit/Debit Cards, Cash, UPI, Online Net Banking.', 40, totalsY + 110);
        doc.text('Thank you for choosing MedPulse Hospital. For billing disputes, contact finance within 7 days.', 40, totalsY + 125);

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }

  /**
   * Generate Lab Report PDF
   */
  static async generateLabReportPdf(reportData: any): Promise<string> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 40, size: 'A4' });
        const buffers: Buffer[] = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', async () => {
          const pdfBuffer = Buffer.concat(buffers);
          const saved = await StorageService.saveFile(
            pdfBuffer,
            `LabReport-${reportData.reportNumber}.pdf`,
            'reports',
            'application/pdf'
          );
          resolve(saved.fileUrl);
        });

        // Header
        doc.fillColor('#0284c7').fontSize(20).text('MEDPULSE CENTRAL DIAGNOSTIC LAB', { align: 'center' });
        doc.fontSize(9).fillColor('#64748b').text('NABL & CAP Accredited Clinical Pathology and Molecular Testing', { align: 'center' });
        doc.moveDown(0.5);
        doc.strokeColor('#0284c7').lineWidth(2).moveTo(40, doc.y).lineTo(555, doc.y).stroke();
        doc.moveDown(1);

        doc.fontSize(14).fillColor('#0f172a').text('DIAGNOSTIC TEST REPORT', { underline: true });
        doc.moveDown(0.5);

        const startY = doc.y;
        doc.fontSize(9).fillColor('#334155');
        doc.text(`Report No: ${reportData.reportNumber}`, 40, startY);
        doc.text(`Date of Test: ${new Date(reportData.completedAt || Date.now()).toLocaleString()}`, 340, startY);

        doc.text(`Patient Name: ${reportData.patientName}`, 40, startY + 16);
        doc.text(`Patient ID: ${reportData.patientId || 'N/A'}`, 340, startY + 16);

        doc.text(`Referring Doctor: Dr. ${reportData.doctorName || 'Attending Physician'}`, 40, startY + 32);
        doc.text(`Sample Type: ${reportData.sampleType || 'Blood / Serum'}`, 340, startY + 32);

        doc.y = startY + 55;
        doc.strokeColor('#e2e8f0').lineWidth(1).moveTo(40, doc.y).lineTo(555, doc.y).stroke();
        doc.moveDown(1);

        // Results Table Header
        const tableTop = doc.y;
        doc.rect(40, tableTop, 515, 20).fill('#f1f5f9');
        doc.fillColor('#0f172a').fontSize(9).font('Helvetica-Bold');
        doc.text('Investigation / Parameter', 45, tableTop + 5);
        doc.text('Observed Value', 240, tableTop + 5);
        doc.text('Biological Ref Interval', 360, tableTop + 5);
        doc.text('Status', 480, tableTop + 5);

        let rowY = tableTop + 24;
        doc.font('Helvetica').fontSize(9).fillColor('#1e293b');

        (reportData.results || []).forEach((res: any) => {
          doc.text(res.testName, 45, rowY, { width: 180 });
          doc.text(`${res.result} ${res.units || ''}`, 240, rowY);
          doc.text(res.normalRange || 'Standard', 360, rowY);

          if (res.flag === 'Abnormal' || res.flag === 'Critical') {
            doc.fillColor('#dc2626').font('Helvetica-Bold').text(res.flag, 480, rowY);
            doc.fillColor('#1e293b').font('Helvetica');
          } else {
            doc.fillColor('#16a34a').text('Normal', 480, rowY);
            doc.fillColor('#1e293b');
          }
          rowY += 22;
        });

        doc.y = Math.max(rowY + 25, 520);
        if (reportData.technicianNotes) {
          doc.fontSize(9).fillColor('#0284c7').text('Pathologist Remarks:');
          doc.fontSize(9).fillColor('#475569').text(reportData.technicianNotes);
          doc.moveDown(1);
        }

        // Signatures
        const footerY = 710;
        doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(380, footerY).lineTo(540, footerY).stroke();
        doc.fontSize(9).fillColor('#0f172a').text('Dr. Sarah Jenkins, MD Pathologist', 380, footerY + 5, { align: 'center', width: 160 });
        doc.fontSize(8).fillColor('#64748b').text('Chief of Clinical Pathology', 380, footerY + 18, { align: 'center', width: 160 });

        doc.fontSize(8).fillColor('#94a3b8').text('Electronically verified laboratory report. In case of unexpected findings, clinical correlation is advised.', 40, 785, { align: 'center' });

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }

  /**
   * Generate Discharge Summary PDF
   */
  static async generateDischargePdf(dischargeData: any): Promise<string> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 40, size: 'A4' });
        const buffers: Buffer[] = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', async () => {
          const pdfBuffer = Buffer.concat(buffers);
          const saved = await StorageService.saveFile(
            pdfBuffer,
            `Discharge-${dischargeData.dischargeNumber}.pdf`,
            'documents',
            'application/pdf'
          );
          resolve(saved.fileUrl);
        });

        // Header
        doc.fillColor('#0284c7').fontSize(20).text('MEDPULSE INPATIENT CARE FACILITY', { align: 'center' });
        doc.fontSize(9).fillColor('#64748b').text('742 Evergreen Medical Park, New York, NY 10001 | 24/7 Desk: +1 (555) 234-5678', { align: 'center' });
        doc.moveDown(0.5);
        doc.strokeColor('#0284c7').lineWidth(1.5).moveTo(40, doc.y).lineTo(555, doc.y).stroke();
        doc.moveDown(1);

        doc.fontSize(14).fillColor('#0f172a').text('PATIENT DISCHARGE SUMMARY', { underline: true });
        doc.moveDown(0.5);

        const startY = doc.y;
        doc.fontSize(9).fillColor('#334155');
        doc.text(`Discharge No: ${dischargeData.dischargeNumber}`, 40, startY);
        doc.text(`Date of Discharge: ${new Date(dischargeData.dischargeDate || Date.now()).toLocaleDateString()}`, 350, startY);

        doc.text(`Patient Name: ${dischargeData.patientName}`, 40, startY + 16);
        doc.text(`Patient ID: ${dischargeData.patientId || 'N/A'}`, 350, startY + 16);

        doc.text(`Attending Physician: Dr. ${dischargeData.doctorName}`, 40, startY + 32);
        doc.text(`Follow-Up Date: ${dischargeData.followUpDate ? new Date(dischargeData.followUpDate).toLocaleDateString() : 'As advised'}`, 350, startY + 32);

        doc.y = startY + 55;
        doc.strokeColor('#e2e8f0').lineWidth(1).moveTo(40, doc.y).lineTo(555, doc.y).stroke();
        doc.moveDown(1);

        // Sections
        doc.fontSize(10).fillColor('#0284c7').text('1. Final Diagnosis:');
        doc.fontSize(9).fillColor('#1e293b').text(dischargeData.finalDiagnosis || 'Recovered following course of treatment.');
        doc.moveDown(0.8);

        doc.fontSize(10).fillColor('#0284c7').text('2. Hospital Course & Treatment Summary:');
        doc.fontSize(9).fillColor('#1e293b').text(dischargeData.treatmentSummary || 'Patient responded well to clinical regimen. Vitals stabilized upon discharge.');
        doc.moveDown(0.8);

        doc.fontSize(10).fillColor('#0284c7').text('3. Discharge Instructions & Diet Advice:');
        doc.fontSize(9).fillColor('#1e293b').text(dischargeData.dischargeInstructions || 'Maintain adequate hydration, avoid strenuous physical activities for 1 week.');
        doc.moveDown(0.8);

        // Medicines table
        if (dischargeData.prescribedMedicines && dischargeData.prescribedMedicines.length > 0) {
          doc.fontSize(10).fillColor('#0284c7').text('4. Discharge Medications:');
          doc.moveDown(0.3);

          const tableTop = doc.y;
          doc.rect(40, tableTop, 515, 18).fill('#f1f5f9');
          doc.fillColor('#0f172a').fontSize(8).font('Helvetica-Bold');
          doc.text('Medicine', 45, tableTop + 4);
          doc.text('Dosage', 180, tableTop + 4);
          doc.text('Frequency', 260, tableTop + 4);
          doc.text('Duration', 340, tableTop + 4);
          doc.text('Instructions', 420, tableTop + 4);

          let rowY = tableTop + 20;
          doc.font('Helvetica').fontSize(8).fillColor('#334155');

          dischargeData.prescribedMedicines.forEach((med: any) => {
            doc.text(med.medicineName, 45, rowY);
            doc.text(med.dosage, 180, rowY);
            doc.text(med.frequency, 260, rowY);
            doc.text(med.duration, 340, rowY);
            doc.text(med.instructions || 'With meals', 420, rowY);
            rowY += 18;
          });
          doc.y = rowY + 10;
        }

        // Doctor Signature
        const footerY = 700;
        doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(380, footerY).lineTo(540, footerY).stroke();
        doc.fontSize(9).fillColor('#0f172a').text(`Dr. ${dischargeData.doctorName}`, 380, footerY + 5, { align: 'center', width: 160 });
        doc.fontSize(8).fillColor('#64748b').text('Treating Physician Signature', 380, footerY + 18, { align: 'center', width: 160 });

        doc.fontSize(8).fillColor('#94a3b8').text('In case of acute symptoms or emergency post-discharge, report immediately to our 24/7 Emergency Unit.', 40, 785, { align: 'center' });

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }
}
